name: GitHub CR Build and Push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # github.repository as <account>/<repo>

concurrency:
  group: ${{ github.ref }}Docker
  cancel-in-progress: true

jobs:
  buildPush:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main')
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: ${{github.event.inputs.id}}
        run: echo Running job ${{github.event.inputs.id}}
      - name: Checkout repository
        uses: actions/checkout@v5

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract FinancialADK Docker metadata
        id: meta1
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/adkfinance

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push FinancialADK Docker image
        id: build-and-push1
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: samples/GCP/FinanceADK/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract ProcessEngineering Docker metadata
        id: meta2
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/adkprocesseng

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push ProcessEngineering Docker image
        id: build-and-push2
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: samples/GCP/ProcessEngineering/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
